ROLES = [
    "USER",
    "ADMIN",
    "SHOP_MANAGER",
    "SALES_AGENT",
    "KITCHEN_STAFF",
    "DELIVERY_AGENT",
    "DRIVER",
    "AGENT"

]

ROLE_OWNER = "ADMIN"
ROLE_MANAGER = "SHOP_MANAGER"
ROLE_SALES_AGENT = "SALES_AGENT"
ROLE_KITCHEN = "KITCHEN_STAFF"
ROLE_DELIVERY_AGENT = "DELIVERY_AGENT"
ROLE_DRIVER = "DRIVER"
ROLE_CUSTOMER = "USER"
ROLE_AGENT = "AGENT"
