"""add missing customer fields to orders

Revision ID: 4bcdc791ac36
Revises: afbf171881a9
Create Date: 2026-07-24 15:57:48.664268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcdc791ac36'
down_revision = 'afbf171881a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('customer_alt_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('delivery_address_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('custom_cake_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('order_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_source')
        batch_op.drop_column('custom_cake_json')
        batch_op.drop_column('delivery_address_json')
        batch_op.drop_column('customer_alt_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
