# """Add availability_status to users

# Revision ID: 8842e1a993a3
# Revises: c159b28a4077
# Create Date: 2026-06-29 23:48:58.764650

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '8842e1a993a3'
# down_revision = 'c159b28a4077'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('orders', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('delivery_agent_id', sa.Integer(), nullable=True))
#         batch_op.add_column(sa.Column('delivery_agent_assigned_by', sa.Integer(), nullable=True))
#         batch_op.add_column(sa.Column('delivery_agent_assigned_at', sa.DateTime(), nullable=True))
#         batch_op.add_column(sa.Column('driver_submitted_at', sa.DateTime(), nullable=True))
#         batch_op.add_column(sa.Column('is_driver_settled', sa.Boolean(), nullable=True))
#         batch_op.add_column(sa.Column('driver_settlement_id', sa.Integer(), nullable=True))
#         batch_op.create_foreign_key(None, 'driver_settlements', ['driver_settlement_id'], ['id'])
#         batch_op.create_foreign_key(None, 'users', ['delivery_agent_id'], ['id'])
#         batch_op.create_foreign_key(None, 'users', ['delivery_agent_assigned_by'], ['id'])

#     # with op.batch_alter_table('users', schema=None) as batch_op:
       

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('users', schema=None) as batch_op:
#         batch_op.drop_column('rating')
#         batch_op.drop_column('availability_status')

#     with op.batch_alter_table('orders', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.drop_column('driver_settlement_id')
#         batch_op.drop_column('is_driver_settled')
#         batch_op.drop_column('driver_submitted_at')
#         batch_op.drop_column('delivery_agent_assigned_at')
#         batch_op.drop_column('delivery_agent_assigned_by')
#         batch_op.drop_column('delivery_agent_id')

#     # ### end Alembic commands ###



"""Add delivery_agent_id, driver_submitted_at to orders;
   add availability_status, rating to users

Revision ID: fix_delivery_agent_and_driver_fields
Revises: c159b28a4077
Create Date: 2025-06-29
"""
from alembic import op
import sqlalchemy as sa

# Revision identifiers
revision = '8842e1a993a3'
down_revision = 'c159b28a4077'
branch_labels = None
depends_on = None


# def upgrade():
#     # ── orders table ─────────────────────────────────────────────────────────

#     # Separate FK for delivery agent (role=DELIVERY_AGENT).
#     # The existing driver_id column now exclusively holds role=DRIVER users.
#     with op.batch_alter_table('orders', schema=None) as batch_op:
#         batch_op.add_column(sa.Column(
#             'delivery_agent_id', sa.Integer(),
#             sa.ForeignKey('users.id'), nullable=True
#         ))
#         batch_op.add_column(sa.Column(
#             'delivery_agent_assigned_by', sa.Integer(),
#             sa.ForeignKey('users.id'), nullable=True
#         ))
#         batch_op.add_column(sa.Column(
#             'delivery_agent_assigned_at', sa.DateTime(), nullable=True
#         ))
#         # Timestamp for when driver submits proof, before agent confirms
#         batch_op.add_column(sa.Column(
#             'driver_submitted_at', sa.DateTime(), nullable=True
#         ))

#     # ── users table ───────────────────────────────────────────────────────────

#     with op.batch_alter_table('users', schema=None) as batch_op:
#         # Driver availability: ONLINE | BUSY | OFFLINE
#         batch_op.add_column(sa.Column(
#             'availability_status', sa.String(length=20),
#             nullable=False, server_default='OFFLINE'
#         ))
#         # Driver rating (0.0 – 5.0)
#         batch_op.add_column(sa.Column(
#             'rating', sa.Float(), nullable=True, server_default='0'
#         ))

#     # ── Migrate existing data: fix orders that had a DELIVERY_AGENT user  ─────
#     # stored in driver_id (the old bug).  Move those rows into delivery_agent_id
#     # and clear driver_id for them.  This is a best-effort heuristic — it uses
#     # the users.role to decide.
#     op.execute("""
#         UPDATE orders
#         SET delivery_agent_id = driver_id,
#             driver_id = NULL
#         WHERE driver_id IN (
#             SELECT id FROM users WHERE role = 'DELIVERY_AGENT'
#         )
#     """)


# def downgrade():
#     with op.batch_alter_table('users', schema=None) as batch_op:
#         batch_op.drop_column('rating')
#         batch_op.drop_column('availability_status')

#     with op.batch_alter_table('orders', schema=None) as batch_op:
#         batch_op.drop_column('driver_submitted_at')
#         batch_op.drop_column('delivery_agent_assigned_at')
#         batch_op.drop_column('delivery_agent_assigned_by')
#         batch_op.drop_column('delivery_agent_id')


def upgrade():

    with op.batch_alter_table("orders") as batch_op:

        batch_op.add_column(
            sa.Column("delivery_agent_id", sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("delivery_agent_assigned_by", sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("delivery_agent_assigned_at", sa.DateTime(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("driver_submitted_at", sa.DateTime(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("is_driver_settled", sa.Boolean(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("driver_settlement_id", sa.Integer(), nullable=True)
        )

        batch_op.create_foreign_key(
            None,
            "users",
            ["delivery_agent_id"],
            ["id"]
        )

        batch_op.create_foreign_key(
            None,
            "users",
            ["delivery_agent_assigned_by"],
            ["id"]
        )

        batch_op.create_foreign_key(
            None,
            "driver_settlements",
            ["driver_settlement_id"],
            ["id"]
        )

    # Do NOT add availability_status again