"""add pickup date and pickup time slot

Revision ID: fc7a8a6381f6
Revises: 20260810merge
Create Date: 2026-08-11 00:01:00.257651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7a8a6381f6'
down_revision = '20260810merge'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_order_items_agent_product_id'), ['agent_product_id'], unique=False)
        batch_op.create_foreign_key(None, 'agent_products', ['agent_product_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pickup_time_slot', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('pickup_time_slot')
        batch_op.drop_column('pickup_date')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_items_agent_product_id'))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('agent_product_id')

    # ### end Alembic commands ###
