"""make user email nullable and clean blank emails

Revision ID: 4308d49cf539
Revises: 1599da761b9c
Create Date: 2026-08-29 17:08:01.210105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4308d49cf539'
down_revision = '1599da761b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###




def upgrade():
    # 1. Relax the constraint first (if it was NOT NULL before)
    op.alter_column('users', 'email',
        existing_type=sa.String(120),
        nullable=True
    )

    # 2. Clean up existing blank-string emails so the unique
    #    constraint stops colliding on them
    op.execute("UPDATE users SET email = NULL WHERE email = ''")

def downgrade():
    op.execute("UPDATE users SET email = '' WHERE email IS NULL")
    op.alter_column('users', 'email',
        existing_type=sa.String(120),
        nullable=False
    )
