"""add category to raw_materials

Revision ID: b6124751f06c
Revises: a1b2c3d4e5f6
Create Date: 2026-08-24 21:59:26.713482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6124751f06c'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('category', sa.String(length=50), nullable=False, server_default='Dry Staples')
        )
        batch_op.alter_column('category', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_column('category')
    # ### end Alembic commands ###



def upgrade():
    op.add_column("agent_products", sa.Column("variants", sa.JSON(), nullable=True))
    op.add_column("agent_products", sa.Column("flavours", sa.JSON(), nullable=True))
    op.drop_column("agent_products", "variant")
    op.drop_column("agent_products", "flavour")

def downgrade():
    op.add_column("agent_products", sa.Column("variant", sa.String(200), nullable=True))
    op.add_column("agent_products", sa.Column("flavour", sa.String(200), nullable=True))
    op.drop_column("agent_products", "variants")
    op.drop_column("agent_products", "flavours")