"""rename created_at to changed_at

Revision ID: c159b28a4077
Revises: 
Create Date: 2026-06-29 19:45:22.706631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c159b28a4077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('delivery_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('driver_share', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['driver_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['paid_by'], ['id'])
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('delivery_amount')
        batch_op.drop_column('postal_code')

    with op.batch_alter_table('driver_settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='expense_payment_source'), nullable=False))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('driver_settlements', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('delivery_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('paid_by')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('driver_share')
        batch_op.drop_column('charge_amount')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
