"""add missing user columns

Revision ID: d6134a0bfdff
Revises: 20260725_push_notify
Create Date: 2026-08-01 21:24:37.251056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6134a0bfdff'
down_revision = '20260725_push_notify'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_products_agent_id'), ['agent_id'], unique=False)

    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('reading_time', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_slug'), ['slug'], unique=True)

    op.create_table('agent_menu_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_menu_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_menu_id'], ['agent_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_menu_id', 'agent_id', name='uq_agent_menu_assignment')
    )
    op.create_table('agent_menu_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_menu_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_menu_id'], ['agent_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_menu_id', 'product_id', name='uq_agent_menu_product')
    )
    with op.batch_alter_table('addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('notification_campaigns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_addons_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('order_addons_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('push_tokens_token_key', type_='unique')

   # Add missing user columns safely.
# IF NOT EXISTS prevents failure when one column already exists.
op.execute("""
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE
""")

op.execute("""
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_by INTEGER NULL
""")

op.execute("""
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS default_discount NUMERIC(5, 2) NOT NULL DEFAULT 0
""")

# Add the self-referencing foreign key only when it does not already exist.
op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_users_created_by_users'
    ) THEN
        ALTER TABLE users
        ADD CONSTRAINT fk_users_created_by_users
        FOREIGN KEY (created_by)
        REFERENCES users(id);
    END IF;
END
$$;
""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_discount')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('push_tokens_token_key', ['token'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('order_addons_total')
        batch_op.drop_column('order_addons_json')

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('notification_campaigns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    with op.batch_alter_table('addons', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.drop_table('agent_menu_products')
    op.drop_table('agent_menu_assignments')
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_slug'))

    op.drop_table('blog')
    with op.batch_alter_table('agent_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_products_agent_id'))

    op.drop_table('agent_products')
    op.drop_table('agent_menus')
    # ### end Alembic commands ###
