"""baseline

Revision ID: e09aa0fd464b
Revises: 
Create Date: 2026-06-30 11:35:37.889897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e09aa0fd464b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('driver_settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='expense_payment_source'), nullable=False))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_agent_assigned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_agent_assigned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_driver_settled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('driver_settlement_id', sa.Integer(), nullable=True))
        batch_op.alter_column('loyalty_coupon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['delivery_agent_assigned_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['delivery_agent_id'], ['id'])
        batch_op.create_foreign_key(None, 'driver_settlements', ['driver_settlement_id'], ['id'])
        batch_op.drop_column('payment_link_created_at')
        batch_op.drop_column('payment_link')
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('products_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('availability_status')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_category_id_fkey'), 'categories', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_link_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('loyalty_coupon',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('driver_settlement_id')
        batch_op.drop_column('is_driver_settled')
        batch_op.drop_column('driver_submitted_at')
        batch_op.drop_column('delivery_agent_assigned_at')
        batch_op.drop_column('delivery_agent_assigned_by')
        batch_op.drop_column('delivery_agent_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('driver_settlements', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
